# Generated by Django 3.2.16 on 2022-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_date', models.DateTimeField()),
                ('post_text', models.CharField(max_length=3000)),
                ('post_image', models.ImageField(upload_to='event_images/')),
            ],
        ),
    ]
